#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           16

bspc config top_padding 	 30
bspc config bottom_padding 	 0
bspc config right_padding 	 12
bspc config left_padding 	 12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#8C8C8C"
bspc config normal_border_color "#3F3F46"
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr &

${HOME}/.fehbg
picom --config ${HOME}/.config/picom/picom.conf &
conky -c ${HOME}/.config/conky/conkyrc.lua &
/usr/bin/xss-lock /usr/bin/screen-locker.lock &
/usr/bin/numlockx on
${HOME}/.config/devol-polybar/launch.sh &
xsettingsd &
gcalcli_reminder &
