#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           16

bspc config top_padding 	 38
bspc config bottom_padding 	 25
bspc config right_padding 	 21
bspc config left_padding 	 21

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#667264"
bspc config normal_border_color "#0F100A"
bspc config focus_follows_pointer true

${HOME}/.fehbg
picom &
conky -c ${HOME}/.config/conky/conkyrc.lua &
/usr/bin/numlockx on
${HOME}/.config/devol-polybar/launch.sh &
