#!/bin/bash

username=$(who | grep '(:0)' | awk '{print $1}')
user_id=$(id -u "${username}")
xauth=$(find "/tmp" -maxdepth 1 -name 'xauth*')

export XDG_RUNTIME_DIR="/run/user/${user_id}"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"

export DISPLAY=":0"

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

repo_name=$1
if [ -z "$repo_name" ]; then
	echo "Could not syncronize machine. Please provide a repository name!" | systemd-cat -t rclone -p err
	exit 1
fi

locker="/tmp/$repo_name-borg.lock"
if mkdir "${locker}" 2>/dev/null; then
	trap 'rm -rf "$locker"' EXIT
else
	echo "⚠️ The borg repository '$repo_name' is already being synchronized!" >&2
	exit 1
fi

notification_id=879875
runuser -l nicolas -c \
  "DISPLAY=${DISPLAY} DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS} XAUTHORITY=${xauth} \
    dunstify -r ${notification_id} \
		--urgency critical \
		'Rclone' 'Sincronizando o repositório \"${repo_name}\" com serviços GCP. Verifique o status do procedimento!'"
if pgrep -x snapborg >/dev/null; then
	echo "Waiting for borg repository unlock files..." | systemd-cat -t rclone -p info
fi

while pgrep -x snapborg >/dev/null; do
	sleep 5
done

echo "Synchronizing borg repository..." | systemd-cat -t rclone -p info
$script_dir/rclone-sync \
	-p /var/log/nicolas/rclone-machine-${repo_name}-repo-backup.log \
	-r "Machine Backup" \
	-b "backup-nicolascbvarch/$repo_name" \
	-s "Repositório \"${repo_name}\" sincronizado em nuvem com sucesso!" \
	-e "Não foi possível sincronizar repositório \"${repo_name}\" em nuvem!" \
	-d /.borg/$repo_name

runuser -l nicolas -c \
  "DISPLAY=${DISPLAY} DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS} XAUTHORITY=${xauth} dunstify -C ${notification_id}"
